/* This file is generated by tools/gen_sizeclasses.ml */
#define POOL_WSIZE 4096
#define POOL_HEADER_WSIZE 6
#define SIZECLASS_MAX 128
#define NUM_SIZECLASSES 32
static const unsigned int wsize_sizeclass[NUM_SIZECLASSES] =
{ 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 17, 19, 22, 25, 28, 32, 33, 37, 42,
  47, 53, 59, 65, 73, 81, 89, 99, 108, 118, 128 };
static const unsigned char wastage_sizeclass[NUM_SIZECLASSES] =
{ 0, 0, 1, 2, 0, 4, 2, 2, 0, 10, 2, 10, 10, 5, 20, 15, 2, 26, 31, 20, 16, 1,
  9, 19, 60, 2, 40, 85, 31, 94, 78, 122 };
static const unsigned char sizeclass_wsize[SIZECLASS_MAX + 1] =
{ 255, 0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 13, 13, 14,
  14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 17, 18, 19, 19, 19, 19, 20, 20,
  20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23,
  23, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26,
  26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28,
  28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30,
  30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31 };
