/* This file is generated by tools/gen_sizeclasses.ml */
#define POOL_WSIZE 4096
#define POOL_HEADER_WSIZE 7
#define SIZECLASS_MAX 128
#define NUM_SIZECLASSES 33

typedef unsigned char sizeclass_t;
static_assert(NUM_SIZECLASSES < (1 << (CHAR_BIT * sizeof(sizeclass_t))), "");

/* The largest size for this size class.
   (A gap is left after smaller objects) */
static const unsigned int wsize_sizeclass[NUM_SIZECLASSES] =
{ /*  0:*/ 1, 2, 3, 4, 5,
  /*  5:*/ 6, 7, 8, 9, 10,
  /* 10:*/ 12, 14, 16, 17, 19,
  /* 15:*/ 22, 25, 28, 32, 33,
  /* 20:*/ 37, 42, 47, 53, 59,
  /* 25:*/ 65, 73, 81, 89, 99,
  /* 30:*/ 108, 118, 128 };

/* The number of padding words to use, at the beginning of a pool
   of this sizeclass, to reach exactly POOL_WSIZE words. */
static const unsigned char wastage_sizeclass[NUM_SIZECLASSES] =
{ /*  0:*/ 0, 1, 0, 1, 4,
  /*  5:*/ 3, 1, 1, 3, 9,
  /* 10:*/ 9, 1, 9, 9, 4,
  /* 15:*/ 19, 14, 1, 25, 30,
  /* 20:*/ 19, 15, 0, 8, 18,
  /* 25:*/ 59, 1, 39, 84, 30,
  /* 30:*/ 93, 77, 121 };

/* Map from (positive) object sizes to size classes. */
static const sizeclass_t sizeclass_wsize[SIZECLASS_MAX + 1] =
{ /*  0:*/ 255, 0, 1, 2, 3,
  /*  5:*/ 4, 5, 6, 7, 8,
  /* 10:*/ 9, 10, 10, 11, 11,
  /* 15:*/ 12, 12, 13, 14, 14,
  /* 20:*/ 15, 15, 15, 16, 16,
  /* 25:*/ 16, 17, 17, 17, 18,
  /* 30:*/ 18, 18, 18, 19, 20,
  /* 35:*/ 20, 20, 20, 21, 21,
  /* 40:*/ 21, 21, 21, 22, 22,
  /* 45:*/ 22, 22, 22, 23, 23,
  /* 50:*/ 23, 23, 23, 23, 24,
  /* 55:*/ 24, 24, 24, 24, 24,
  /* 60:*/ 25, 25, 25, 25, 25,
  /* 65:*/ 25, 26, 26, 26, 26,
  /* 70:*/ 26, 26, 26, 26, 27,
  /* 75:*/ 27, 27, 27, 27, 27,
  /* 80:*/ 27, 27, 28, 28, 28,
  /* 85:*/ 28, 28, 28, 28, 28,
  /* 90:*/ 29, 29, 29, 29, 29,
  /* 95:*/ 29, 29, 29, 29, 29,
  /*100:*/ 30, 30, 30, 30, 30,
  /*105:*/ 30, 30, 30, 30, 31,
  /*110:*/ 31, 31, 31, 31, 31,
  /*115:*/ 31, 31, 31, 31, 32,
  /*120:*/ 32, 32, 32, 32, 32,
  /*125:*/ 32, 32, 32, 32 };
